[build]
  command = "npm install --legacy-peer-deps && node set-env.js && npx ng build --configuration production"
  publish = "dist/uat-platform/browser"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
